spring:
  application:
    name: bank-management-system

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  hikari:
    minimum-idle: 3
    maximum-pool-size: 6
    idle-timeout: 30000
    max-lifetime: 2000000
    connection-timeout: 60000
  jpa:
    show-sql: true
    open-in-view: true

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

cache:
  redis:
    account:
      ttl: 120 #seconds

server:
  port: 8080

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /api-doc
  swagger-ui:
    path: /swagger-ui.html

bank:
  withdrawal:
    daily-limit: 5000