spring:
  application:
    name: bank-management-system
  messages:
    encoding: UTF-8
    basename: i18n/messages

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  hikari:
    minimum-idle: 3
    maximum-pool-size: 6
    idle-timeout: 30000
    max-lifetime: 2000000
    connection-timeout: 60000
  jpa:
    show-sql: true
    open-in-view: true

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

cache:
  redis:
    account:
      ttl: 120 #seconds
    telegram:
      ttl: 120 #seconds

server:
  port: 8080

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

bank:
  withdrawal:
    daily-limit: 5000

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}   # Environment variable tÃ¶vsiyÉ™ olunur
    username: Springelcin_test_bot

    welcome-message: | 
      âœ… Salam
      ğŸ¦ MyBank sisteminÉ™ xoÅŸ gÉ™lmisiniz!

      ğŸ“± Telegram hesabÄ±nÄ±z uÄŸurla É™laqÉ™lÉ™ndirildi.

      ğŸ” ArtÄ±q:
      â€¢ BÃ¼tÃ¼n OTP kodlarÄ± burada alÄ±nacaq
      â€¢ ÆmÉ™liyyat bildiriÅŸlÉ™ri buraya gÉ™lÉ™cÉ™k
      â€¢ TÉ™hlÃ¼kÉ™sizlik xÉ™bÉ™rdarlÄ±qlarÄ± burada olacaq
      âš ï¸ Vacib: OTP kodlarÄ±nÄ± heÃ§ kimlÉ™ paylaÅŸmayÄ±n!